#!/bin/sh

set -e

function godoc_version_argument() {
    case $1 in
        1.20 | 1.21)
            echo "--build-arg GODOC_VERSION=v0.24.0"
            ;;
        1.22)
            echo "--build-arg GODOC_VERSION=v0.30.0"
            ;;
        *)
            echo ""
            ;;
    esac
}

for v in 1.20 1.21 1.22 1.23 1.24; do
    docker build . --build-arg GO_VERSION=$v $(godoc_version_argument $v) --no-cache -t robtimus/go-toolset:$v
    docker run --rm robtimus/go-toolset:$v sh -c "go version && golangci-lint --version && gosec --version"
done
for v in 1.20 1.21 1.22 1.23 1.24; do
    docker push robtimus/go-toolset:$v
done
docker tag robtimus/go-toolset:1.24 robtimus/go-toolset && docker push robtimus/go-toolset
