#!/bin/sh

set -e

go_versions="1.20 1.21 1.22 1.23 1.24"
go_latest_version="1.24"

if [ $# != 0 ]; then
    go_versions="$*"
fi

function godoc_version_argument() {
    case $1 in
        1.20 | 1.21)
            echo "--build-arg GODOC_VERSION=v0.24.0"
            ;;
        1.22)
            echo "--build-arg GODOC_VERSION=v0.30.0"
            ;;
        *)
            echo ""
            ;;
    esac
}

for v in $go_versions; do
    docker build . --build-arg GO_VERSION=$v $(godoc_version_argument $v) --no-cache -t robtimus/go-toolset:$v
    docker run --rm robtimus/go-toolset:$v sh -c "go version && golangci-lint --version && gosec --version"
done
for v in $go_versions; do
    docker push robtimus/go-toolset:$v
done
docker tag robtimus/go-toolset:$go_latest_version robtimus/go-toolset && docker push robtimus/go-toolset
